[2024-08-21 22:00:02] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-19/prod/2024-08-19_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-21 22:00:02
Arguments: Namespace(date='2024-08-19', is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/')
Processing distillation data for date: 2024-08-19
Input folder: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-19
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-19/raw/single_True_rag_True
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 109, in <module>
    distillator.get_distillation_data(args.date)
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 39, in get_distillation_data
    utils.create_directory(outfolder)
    ^^^^^
NameError: name 'utils' is not defined
[INFO] end_time: 2024-08-21 22:00:05  
[INFO] duration: 0 min 
[2024-08-22 22:00:02] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-20/prod/2024-08-20_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-22 22:00:02
/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/data_processing.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filter_df['task_name'] = np.select(task_conditions, task_choices, default=None)
Arguments: Namespace(date='2024-08-20', is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/')
Processing distillation data for date: 2024-08-20
Input folder: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-20
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-20/raw/single_True_rag_True
Reading input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-20/prod/2024-08-20_rule_labeled.csv.gpt_labeled.csv
Saved chunk 1 to /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-20/raw/single_True_rag_True/split_data/chunk_1.csv
Regenerating missing GPT-4 file for split data file: chunk_1.csv
Reading oneshot prompt from: /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt
Reading oneshot prompt done.
Building prompts for dataframe entries.
Calling GPT-4 API
剩余case 139 / 139
  0%|          | 0/139 [00:00<?, ?it/s]  1%|          | 1/139 [00:22<52:18, 22.75s/it]  4%|▍         | 6/139 [00:34<10:53,  4.91s/it]  5%|▌         | 7/139 [00:35<09:08,  4.15s/it]  6%|▋         | 9/139 [00:38<06:32,  3.02s/it]  7%|▋         | 10/139 [00:50<10:29,  4.88s/it]  9%|▊         | 12/139 [01:01<11:06,  5.25s/it] 11%|█         | 15/139 [01:09<08:30,  4.12s/it] 13%|█▎        | 18/139 [01:17<06:57,  3.45s/it] 14%|█▎        | 19/139 [01:20<07:00,  3.51s/it] 14%|█▍        | 20/139 [01:38<11:54,  6.01s/it] 17%|█▋        | 23/139 [01:47<09:15,  4.79s/it] 19%|█▉        | 27/139 [01:58<07:14,  3.88s/it] 22%|██▏       | 31/139 [02:10<06:13,  3.46s/it] 23%|██▎       | 32/139 [02:39<11:51,  6.65s/it] 29%|██▉       | 40/139 [02:53<06:11,  3.76s/it] 30%|███       | 42/139 [02:56<05:25,  3.35s/it] 32%|███▏      | 45/139 [03:11<06:00,  3.83s/it] 36%|███▌      | 50/139 [03:13<03:39,  2.47s/it] 37%|███▋      | 51/139 [03:46<08:07,  5.54s/it] 41%|████      | 57/139 [03:50<04:28,  3.28s/it] 42%|████▏     | 59/139 [03:51<03:44,  2.81s/it] 43%|████▎     | 60/139 [04:06<05:28,  4.16s/it] 45%|████▌     | 63/139 [04:26<06:23,  5.05s/it] 50%|████▉     | 69/139 [04:34<03:48,  3.26s/it] 52%|█████▏    | 72/139 [04:39<03:11,  2.86s/it] 53%|█████▎    | 73/139 [04:42<03:07,  2.85s/it] 54%|█████▍    | 75/139 [04:49<03:14,  3.04s/it] 55%|█████▍    | 76/139 [04:51<02:55,  2.79s/it] 55%|█████▌    | 77/139 [04:57<03:29,  3.38s/it] 56%|█████▌    | 78/139 [05:05<04:24,  4.34s/it] 58%|█████▊    | 80/139 [05:09<03:28,  3.53s/it] 59%|█████▉    | 82/139 [05:10<02:18,  2.43s/it] 60%|█████▉    | 83/139 [05:17<03:07,  3.35s/it] 60%|██████    | 84/139 [05:25<03:53,  4.25s/it] 62%|██████▏   | 86/139 [05:30<03:10,  3.59s/it] 63%|██████▎   | 87/139 [05:43<04:50,  5.59s/it] 64%|██████▍   | 89/139 [05:52<04:27,  5.35s/it] 66%|██████▌   | 92/139 [05:54<02:28,  3.16s/it] 67%|██████▋   | 93/139 [05:58<02:30,  3.28s/it] 68%|██████▊   | 94/139 [06:00<02:22,  3.17s/it] 68%|██████▊   | 95/139 [06:06<02:38,  3.60s/it] 69%|██████▉   | 96/139 [06:06<02:03,  2.87s/it] 70%|██████▉   | 97/139 [06:11<02:25,  3.48s/it] 71%|███████   | 98/139 [06:14<02:07,  3.12s/it] 72%|███████▏  | 100/139 [06:22<02:22,  3.65s/it] 73%|███████▎  | 102/139 [06:29<02:14,  3.64s/it] 75%|███████▍  | 104/139 [06:30<01:28,  2.52s/it] 76%|███████▋  | 106/139 [06:33<01:08,  2.09s/it] 77%|███████▋  | 107/139 [06:37<01:18,  2.45s/it] 78%|███████▊  | 109/139 [06:44<01:25,  2.85s/it] 79%|███████▉  | 110/139 [06:55<02:09,  4.45s/it] 81%|████████  | 112/139 [06:58<01:31,  3.40s/it] 81%|████████▏ | 113/139 [07:11<02:18,  5.31s/it] 83%|████████▎ | 116/139 [07:15<01:19,  3.46s/it] 84%|████████▍ | 117/139 [07:25<01:45,  4.80s/it] 86%|████████▌ | 119/139 [07:31<01:23,  4.17s/it] 86%|████████▋ | 120/139 [07:33<01:10,  3.71s/it] 87%|████████▋ | 121/139 [07:35<00:58,  3.26s/it] 88%|████████▊ | 122/139 [07:41<01:08,  4.05s/it] 88%|████████▊ | 123/139 [07:52<01:29,  5.60s/it] 89%|████████▉ | 124/139 [08:04<01:50,  7.33s/it] 91%|█████████▏| 127/139 [08:05<00:43,  3.60s/it] 92%|█████████▏| 128/139 [08:08<00:38,  3.46s/it] 93%|█████████▎| 129/139 [08:10<00:33,  3.33s/it] 94%|█████████▎| 130/139 [08:13<00:27,  3.03s/it] 94%|█████████▍| 131/139 [08:13<00:18,  2.34s/it] 95%|█████████▍| 132/139 [08:14<00:13,  1.98s/it] 96%|█████████▌| 133/139 [08:17<00:13,  2.19s/it] 96%|█████████▋| 134/139 [08:20<00:12,  2.48s/it] 97%|█████████▋| 135/139 [08:23<00:10,  2.58s/it] 98%|█████████▊| 136/139 [08:28<00:10,  3.48s/it] 99%|█████████▊| 137/139 [08:33<00:07,  3.82s/it]100%|██████████| 139/139 [08:36<00:00,  2.68s/it]100%|██████████| 139/139 [08:36<00:00,  3.71s/it]
Parsing GPT-4 response
All GPT-4 files are generated and valid. Total files: 1
[INFO] end_time: 2024-08-22 22:10:48  
[INFO] duration: 10 min 
[2024-08-23 22:00:02] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-21/prod/2024-08-21_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-23 22:00:02
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 52, in get_distillation_data
    filter_df = DataFilter.get_task_usecols(filter_df)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/data_processing.py", line 34, in get_task_usecols
    filter_df['task_name'] = np.select(task_conditions, task_choices, default=None)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/numpy/lib/function_base.py", line 813, in select
    raise ValueError(
ValueError: list of cases must be same length as list of conditions
Arguments: Namespace(date='2024-08-21', is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/')
Processing distillation data for date: 2024-08-21
Input folder: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-21
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-21/raw/single_True_rag_True
Reading input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-21/prod/2024-08-21_rule_labeled.csv.gpt_labeled.csv
Exception occurred while processing file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-21/prod/2024-08-21_rule_labeled.csv.gpt_labeled.csv
Data list is empty, no valid dataframes read.
[INFO] end_time: 2024-08-23 22:00:12  
[INFO] duration: 0 min 
[2024-08-24 22:00:02] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-22/prod/2024-08-22_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-24 22:00:02
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 52, in get_distillation_data
    filter_df = DataFilter.get_task_usecols(filter_df)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/data_processing.py", line 34, in get_task_usecols
    filter_df['task_name'] = np.select(task_conditions, task_choices, default=None)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/numpy/lib/function_base.py", line 813, in select
    raise ValueError(
ValueError: list of cases must be same length as list of conditions
Arguments: Namespace(date='2024-08-22', is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/')
Processing distillation data for date: 2024-08-22
Input folder: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-22
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-22/raw/single_True_rag_True
Reading input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-22/prod/2024-08-22_rule_labeled.csv.gpt_labeled.csv
Exception occurred while processing file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-22/prod/2024-08-22_rule_labeled.csv.gpt_labeled.csv
Data list is empty, no valid dataframes read.
[INFO] end_time: 2024-08-24 22:00:10  
[INFO] duration: 0 min 
[2024-08-25 22:00:01] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-23/prod/2024-08-23_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-25 22:00:01
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 52, in get_distillation_data
    filter_df = DataFilter.get_task_usecols(filter_df)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/data_processing.py", line 34, in get_task_usecols
    filter_df['task_name'] = np.select(task_conditions, task_choices, default=None)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/numpy/lib/function_base.py", line 813, in select
    raise ValueError(
ValueError: list of cases must be same length as list of conditions
Arguments: Namespace(date='2024-08-23', is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/')
Processing distillation data for date: 2024-08-23
Input folder: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-23
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-23/raw/single_True_rag_True
Reading input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-23/prod/2024-08-23_rule_labeled.csv.gpt_labeled.csv
Exception occurred while processing file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-23/prod/2024-08-23_rule_labeled.csv.gpt_labeled.csv
Data list is empty, no valid dataframes read.
[INFO] end_time: 2024-08-25 22:00:09  
[INFO] duration: 0 min 
[2024-08-26 22:00:01] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-24/prod/2024-08-24_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-26 22:00:01
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 52, in get_distillation_data
    filter_df = DataFilter.get_task_usecols(filter_df)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/data_processing.py", line 34, in get_task_usecols
    filter_df['task_name'] = np.select(task_conditions, task_choices, default=None)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/numpy/lib/function_base.py", line 813, in select
    raise ValueError(
ValueError: list of cases must be same length as list of conditions
Arguments: Namespace(date='2024-08-24', is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/')
Processing distillation data for date: 2024-08-24
Input folder: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-24
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-24/raw/single_True_rag_True
Reading input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-24/prod/2024-08-24_rule_labeled.csv.gpt_labeled.csv
Exception occurred while processing file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-24/prod/2024-08-24_rule_labeled.csv.gpt_labeled.csv
Data list is empty, no valid dataframes read.
[INFO] end_time: 2024-08-26 22:00:10  
[INFO] duration: 0 min 
[2024-08-27 22:00:02] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-25/prod/2024-08-25_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-27 22:00:02
Arguments: Namespace(date='2024-08-25', is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/')
Processing distillation data for date: 2024-08-25
Input folder: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-25
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-25/raw/single_True_rag_True
Reading input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-25/prod/2024-08-25_rule_labeled.csv.gpt_labeled.csv
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 122, in <module>
    distillator.get_distillation_data(args.date)
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 81, in get_distillation_data
    self.check_and_generate_gpt4_files(outfolder, prompt_path)
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/base_distillation.py", line 77, in check_and_generate_gpt4_files
    if not missing_files and (wrong_data_count / total_data_count) <= 0.5:
                              ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
[INFO] end_time: 2024-08-27 22:00:10  
[INFO] duration: 0 min 
[2024-08-28 22:00:02] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-26/prod/2024-08-26_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-28 22:00:02
/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/data_processing.py:52: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filter_df['task_name'] = np.select(task_conditions, task_choices, default='正常数据')
Arguments: Namespace(date='2024-08-26', is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/')
Processing distillation data for date: 2024-08-26
Input folder: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-26
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-26/raw/single_True_rag_True
Reading input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-26/prod/2024-08-26_rule_labeled.csv.gpt_labeled.csv
Saved chunk 1 to /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-26/raw/single_True_rag_True/split_data/chunk_1.csv
Regenerating missing GPT-4 file for split data file: chunk_1.csv
Reading oneshot prompt from: /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt
Reading oneshot prompt done.
Building prompts for dataframe entries.
Calling GPT-4 API
剩余case 89 / 89
  0%|          | 0/89 [00:00<?, ?it/s]  1%|          | 1/89 [00:12<18:21, 12.51s/it]  2%|▏         | 2/89 [00:21<15:32, 10.72s/it]  9%|▉         | 8/89 [00:31<04:10,  3.09s/it] 12%|█▏        | 11/89 [00:49<05:30,  4.24s/it] 17%|█▋        | 15/89 [01:24<07:25,  6.03s/it] 21%|██▏       | 19/89 [01:27<04:49,  4.13s/it] 25%|██▍       | 22/89 [01:36<04:10,  3.74s/it] 26%|██▌       | 23/89 [01:36<03:39,  3.32s/it] 27%|██▋       | 24/89 [01:39<03:32,  3.26s/it] 28%|██▊       | 25/89 [01:40<03:06,  2.92s/it] 29%|██▉       | 26/89 [01:50<04:25,  4.22s/it] 33%|███▎      | 29/89 [01:51<02:26,  2.44s/it] 34%|███▎      | 30/89 [01:51<02:03,  2.10s/it] 35%|███▍      | 31/89 [01:56<02:37,  2.71s/it] 37%|███▋      | 33/89 [02:08<03:37,  3.89s/it] 40%|████      | 36/89 [02:11<02:16,  2.57s/it] 42%|████▏     | 37/89 [02:26<04:12,  4.85s/it] 45%|████▍     | 40/89 [02:29<02:36,  3.20s/it] 47%|████▋     | 42/89 [02:30<01:50,  2.35s/it] 48%|████▊     | 43/89 [02:32<01:48,  2.36s/it] 49%|████▉     | 44/89 [02:37<02:10,  2.90s/it] 51%|█████     | 45/89 [03:36<11:08, 15.19s/it] 73%|███████▎  | 65/89 [03:44<00:58,  2.43s/it] 79%|███████▊  | 70/89 [04:00<00:49,  2.61s/it] 87%|████████▋ | 77/89 [04:05<00:24,  2.00s/it] 90%|████████▉ | 80/89 [04:09<00:16,  1.86s/it] 92%|█████████▏| 82/89 [04:13<00:13,  1.90s/it] 93%|█████████▎| 83/89 [04:18<00:13,  2.17s/it] 96%|█████████▌| 85/89 [04:24<00:09,  2.37s/it] 98%|█████████▊| 87/89 [04:25<00:03,  1.89s/it]100%|██████████| 89/89 [04:26<00:00,  1.64s/it]100%|██████████| 89/89 [04:26<00:00,  3.00s/it]
Parsing GPT-4 response
All GPT-4 files are generated and valid. Total files: 1
[INFO] end_time: 2024-08-28 22:06:39  
[INFO] duration: 6 min 
[2024-08-29 22:00:01] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-23/prod/2024-08-23_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-29 22:00:01
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /opt/conda/envs/rhm_env did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
Arguments: Namespace(is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-23/prod/2024-08-23_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh')
Processing distillation data for date: 2024-08-23
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-23/prod/2024-08-23_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-23/raw/single_True_rag_True
Saved chunk 1 to /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-23/raw/single_True_rag_True/split_data/chunk_1.csv
All GPT-4 files are generated and valid. Total files: 1
[INFO] end_time: 2024-08-29 22:00:21
[INFO] duration: 0 min 
[2024-08-30 22:00:02] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-28/prod/2024-08-28_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-30 22:00:02
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /opt/conda/envs/rhm_env did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
Arguments: Namespace(is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-28/prod/2024-08-28_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh')
Processing distillation data for date: 2024-08-28
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-28/prod/2024-08-28_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-28/raw/single_True_rag_True
Saved chunk 1 to /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-28/raw/single_True_rag_True/split_data/chunk_1.csv
Regenerating missing GPT-4 file for split data file: chunk_1.csv
Reading oneshot prompt from: /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt
Reading oneshot prompt done.
Building prompts for dataframe entries.
Calling GPT-4 API
剩余case 102 / 102
  0%|          | 0/102 [00:00<?, ?it/s]  1%|          | 1/102 [00:08<14:30,  8.62s/it]  2%|▏         | 2/102 [00:13<10:17,  6.18s/it]  4%|▍         | 4/102 [00:44<19:57, 12.22s/it] 10%|▉         | 10/102 [01:04<08:48,  5.75s/it] 12%|█▏        | 12/102 [01:13<08:00,  5.34s/it] 15%|█▍        | 15/102 [01:13<05:05,  3.52s/it] 16%|█▌        | 16/102 [01:25<06:49,  4.76s/it] 20%|█▉        | 20/102 [01:30<04:13,  3.09s/it] 21%|██        | 21/102 [01:36<04:48,  3.56s/it] 24%|██▎       | 24/102 [01:41<03:41,  2.84s/it] 25%|██▌       | 26/102 [01:48<03:52,  3.06s/it] 27%|██▋       | 28/102 [02:29<09:33,  7.75s/it] 35%|███▌      | 36/102 [02:44<04:35,  4.18s/it] 39%|███▉      | 40/102 [02:54<03:45,  3.64s/it] 40%|████      | 41/102 [03:17<05:41,  5.59s/it] 46%|████▌     | 47/102 [03:17<02:48,  3.06s/it] 47%|████▋     | 48/102 [03:23<02:56,  3.27s/it] 50%|█████     | 51/102 [03:31<02:38,  3.11s/it] 51%|█████     | 52/102 [03:59<05:12,  6.25s/it] 55%|█████▍    | 56/102 [04:38<05:53,  7.69s/it] 70%|██████▉   | 71/102 [04:43<01:21,  2.62s/it] 72%|███████▏  | 73/102 [04:45<01:10,  2.43s/it] 75%|███████▍  | 76/102 [04:48<00:55,  2.15s/it] 76%|███████▋  | 78/102 [04:49<00:45,  1.89s/it] 77%|███████▋  | 79/102 [04:59<01:01,  2.69s/it] 83%|████████▎ | 85/102 [05:02<00:27,  1.64s/it] 86%|████████▋ | 88/102 [05:21<00:39,  2.81s/it] 90%|█████████ | 92/102 [05:24<00:21,  2.14s/it] 92%|█████████▏| 94/102 [05:35<00:22,  2.81s/it] 95%|█████████▌| 97/102 [05:44<00:14,  2.89s/it] 98%|█████████▊| 100/102 [05:45<00:04,  2.14s/it] 99%|█████████▉| 101/102 [05:50<00:02,  2.47s/it]100%|██████████| 102/102 [05:54<00:00,  2.76s/it]100%|██████████| 102/102 [05:54<00:00,  3.48s/it]
chatgpt api 调用异常：Expecting value: line 1 column 1 (char 0)
chatgpt api 调用异常：Expecting value: line 1 column 1 (char 0)
chatgpt api 调用异常：Expecting value: line 1 column 1 (char 0)
Parsing GPT-4 response
All GPT-4 files are generated and valid. Total files: 1
[INFO] end_time: 2024-08-30 22:08:21
[INFO] duration: 8 min 
[2024-08-31 22:00:02] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-29/prod/2024-08-29_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-31 22:00:02
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /opt/conda/envs/rhm_env did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
Arguments: Namespace(is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-29/prod/2024-08-29_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh')
Processing distillation data for date: 2024-08-29
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-29/prod/2024-08-29_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-29/raw/single_True_rag_True
Saved chunk 1 to /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-29/raw/single_True_rag_True/split_data/chunk_1.csv
Regenerating missing GPT-4 file for split data file: chunk_1.csv
Reading oneshot prompt from: /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt
Reading oneshot prompt done.
Building prompts for dataframe entries.
Calling GPT-4 API
剩余case 117 / 117
  0%|          | 0/117 [00:00<?, ?it/s]  1%|          | 1/117 [00:10<20:49, 10.77s/it]  2%|▏         | 2/117 [00:12<10:45,  5.62s/it]  3%|▎         | 4/117 [00:13<04:12,  2.23s/it]  4%|▍         | 5/117 [00:15<04:19,  2.32s/it]  5%|▌         | 6/117 [00:18<04:18,  2.33s/it]  7%|▋         | 8/117 [00:19<02:40,  1.48s/it]  8%|▊         | 9/117 [00:21<02:52,  1.59s/it]  9%|▊         | 10/117 [00:22<02:41,  1.51s/it] 10%|█         | 12/117 [00:26<03:00,  1.72s/it] 11%|█         | 13/117 [00:30<03:55,  2.26s/it] 12%|█▏        | 14/117 [00:33<04:04,  2.38s/it] 14%|█▎        | 16/117 [00:33<02:25,  1.44s/it] 15%|█▍        | 17/117 [00:37<03:17,  1.97s/it] 15%|█▌        | 18/117 [00:38<03:01,  1.84s/it] 16%|█▌        | 19/117 [00:39<02:27,  1.50s/it] 17%|█▋        | 20/117 [00:39<02:04,  1.28s/it] 18%|█▊        | 21/117 [00:44<03:33,  2.22s/it] 19%|█▉        | 22/117 [00:54<07:18,  4.61s/it] 21%|██▏       | 25/117 [00:59<04:22,  2.85s/it] 23%|██▎       | 27/117 [01:03<04:00,  2.68s/it] 25%|██▍       | 29/117 [01:14<05:11,  3.54s/it] 29%|██▉       | 34/117 [01:19<02:55,  2.11s/it] 31%|███       | 36/117 [01:23<02:48,  2.09s/it] 32%|███▏      | 38/117 [01:27<02:48,  2.13s/it] 33%|███▎      | 39/117 [01:27<02:21,  1.82s/it] 35%|███▌      | 41/117 [01:28<01:50,  1.46s/it] 36%|███▌      | 42/117 [01:42<04:36,  3.69s/it] 38%|███▊      | 45/117 [01:47<03:18,  2.76s/it] 40%|████      | 47/117 [01:53<03:18,  2.84s/it] 42%|████▏     | 49/117 [02:00<03:21,  2.96s/it] 44%|████▎     | 51/117 [02:01<02:31,  2.29s/it] 44%|████▍     | 52/117 [02:03<02:21,  2.18s/it] 45%|████▌     | 53/117 [02:09<03:11,  2.99s/it] 47%|████▋     | 55/117 [02:10<02:06,  2.04s/it] 49%|████▊     | 57/117 [02:11<01:32,  1.54s/it] 50%|████▉     | 58/117 [02:13<01:38,  1.68s/it] 51%|█████▏    | 60/117 [02:14<01:14,  1.31s/it] 52%|█████▏    | 61/117 [02:16<01:17,  1.39s/it] 54%|█████▍    | 63/117 [02:17<00:57,  1.06s/it] 55%|█████▍    | 64/117 [02:18<00:57,  1.08s/it] 56%|█████▌    | 65/117 [02:21<01:20,  1.55s/it] 57%|█████▋    | 67/117 [02:24<01:09,  1.38s/it] 58%|█████▊    | 68/117 [02:24<00:54,  1.11s/it] 59%|█████▉    | 69/117 [02:27<01:15,  1.56s/it] 60%|█████▉    | 70/117 [02:27<00:58,  1.24s/it] 62%|██████▏   | 72/117 [02:30<01:05,  1.46s/it] 63%|██████▎   | 74/117 [02:31<00:40,  1.06it/s] 65%|██████▍   | 76/117 [02:35<00:54,  1.32s/it] 67%|██████▋   | 78/117 [02:36<00:42,  1.09s/it] 68%|██████▊   | 80/117 [02:44<01:15,  2.03s/it] 74%|███████▍  | 87/117 [02:45<00:26,  1.13it/s] 76%|███████▌  | 89/117 [02:47<00:24,  1.15it/s] 78%|███████▊  | 91/117 [02:54<00:38,  1.47s/it] 81%|████████  | 95/117 [02:57<00:26,  1.21s/it] 82%|████████▏ | 96/117 [03:00<00:28,  1.36s/it] 84%|████████▍ | 98/117 [03:02<00:25,  1.33s/it] 85%|████████▍ | 99/117 [03:07<00:33,  1.85s/it] 85%|████████▌ | 100/117 [03:09<00:34,  2.00s/it] 88%|████████▊ | 103/117 [03:12<00:20,  1.44s/it] 90%|████████▉ | 105/117 [03:16<00:20,  1.73s/it] 92%|█████████▏| 108/117 [03:21<00:15,  1.68s/it] 94%|█████████▍| 110/117 [03:27<00:14,  2.00s/it] 97%|█████████▋| 113/117 [03:29<00:05,  1.48s/it] 97%|█████████▋| 114/117 [03:30<00:04,  1.48s/it] 98%|█████████▊| 115/117 [03:32<00:03,  1.59s/it]100%|██████████| 117/117 [03:34<00:00,  1.41s/it]100%|██████████| 117/117 [03:34<00:00,  1.84s/it]
chatgpt api 调用异常：Expecting value: line 1 column 1 (char 0)
Parsing GPT-4 response
All GPT-4 files are generated and valid. Total files: 1
[INFO] end_time: 2024-08-31 22:06:00
[INFO] duration: 5 min 
[2024-09-01 22:00:02] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-30/prod/2024-08-30_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-09-01 22:00:02
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /opt/conda/envs/rhm_env did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
Arguments: Namespace(is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-30/prod/2024-08-30_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh')
Processing distillation data for date: 2024-08-30
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-30/prod/2024-08-30_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-30/raw/single_True_rag_True
Saved chunk 1 to /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-30/raw/single_True_rag_True/split_data/chunk_1.csv
Regenerating missing GPT-4 file for split data file: chunk_1.csv
Reading oneshot prompt from: /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt
Reading oneshot prompt done.
Building prompts for dataframe entries.
Calling GPT-4 API
剩余case 90 / 90
  0%|          | 0/90 [00:00<?, ?it/s]  1%|          | 1/90 [00:09<13:39,  9.21s/it]  3%|▎         | 3/90 [00:09<03:41,  2.54s/it]  4%|▍         | 4/90 [00:14<04:43,  3.29s/it]  8%|▊         | 7/90 [00:22<03:57,  2.86s/it] 10%|█         | 9/90 [00:33<05:23,  3.99s/it] 13%|█▎        | 12/90 [00:41<04:20,  3.34s/it] 17%|█▋        | 15/90 [00:45<03:17,  2.63s/it] 19%|█▉        | 17/90 [00:47<02:34,  2.11s/it] 21%|██        | 19/90 [00:47<01:54,  1.61s/it] 22%|██▏       | 20/90 [00:59<03:47,  3.25s/it] 26%|██▌       | 23/90 [01:04<02:49,  2.53s/it] 27%|██▋       | 24/90 [01:04<02:29,  2.27s/it] 28%|██▊       | 25/90 [01:06<02:20,  2.16s/it] 29%|██▉       | 26/90 [01:15<03:48,  3.56s/it] 30%|███       | 27/90 [01:16<03:06,  2.96s/it] 34%|███▍      | 31/90 [01:23<02:17,  2.33s/it] 37%|███▋      | 33/90 [01:34<03:04,  3.24s/it] 41%|████      | 37/90 [01:41<02:16,  2.57s/it] 44%|████▍     | 40/90 [01:44<01:43,  2.06s/it] 46%|████▌     | 41/90 [01:58<02:55,  3.58s/it] 52%|█████▏    | 47/90 [01:59<01:17,  1.81s/it] 53%|█████▎    | 48/90 [02:00<01:09,  1.65s/it] 54%|█████▍    | 49/90 [02:04<01:19,  1.95s/it] 56%|█████▌    | 50/90 [02:08<01:35,  2.40s/it] 59%|█████▉    | 53/90 [02:09<00:57,  1.56s/it] 60%|██████    | 54/90 [02:11<00:57,  1.59s/it] 61%|██████    | 55/90 [02:14<01:07,  1.92s/it] 63%|██████▎   | 57/90 [02:15<00:41,  1.26s/it] 64%|██████▍   | 58/90 [02:15<00:34,  1.09s/it] 66%|██████▌   | 59/90 [02:17<00:37,  1.21s/it] 67%|██████▋   | 60/90 [02:17<00:31,  1.05s/it] 68%|██████▊   | 61/90 [02:19<00:38,  1.34s/it] 69%|██████▉   | 62/90 [02:20<00:31,  1.12s/it] 70%|███████   | 63/90 [02:22<00:34,  1.27s/it] 72%|███████▏  | 65/90 [02:26<00:44,  1.78s/it] 73%|███████▎  | 66/90 [02:31<01:01,  2.58s/it] 78%|███████▊  | 70/90 [02:32<00:23,  1.18s/it] 79%|███████▉  | 71/90 [02:34<00:25,  1.35s/it] 80%|████████  | 72/90 [02:35<00:21,  1.21s/it] 81%|████████  | 73/90 [02:38<00:27,  1.62s/it] 83%|████████▎ | 75/90 [02:45<00:36,  2.43s/it] 87%|████████▋ | 78/90 [02:55<00:33,  2.77s/it] 89%|████████▉ | 80/90 [02:55<00:19,  1.95s/it] 90%|█████████ | 81/90 [03:03<00:26,  2.93s/it] 93%|█████████▎| 84/90 [03:05<00:11,  2.00s/it] 94%|█████████▍| 85/90 [03:13<00:15,  3.10s/it] 99%|█████████▉| 89/90 [03:14<00:01,  1.68s/it]100%|██████████| 90/90 [03:19<00:00,  2.20s/it]100%|██████████| 90/90 [03:19<00:00,  2.22s/it]
Parsing GPT-4 response
All GPT-4 files are generated and valid. Total files: 1
[INFO] end_time: 2024-09-01 22:05:43
[INFO] duration: 5 min 
[2024-09-02 22:00:02] /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/run_crontab_distillation_log_raw_single_rag.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-31/prod/2024-08-31_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-09-02 22:00:02
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /opt/conda/envs/rhm_env did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
Arguments: Namespace(is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-31/prod/2024-08-31_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh')
Processing distillation data for date: 2024-08-31
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data/2024-08-31/prod/2024-08-31_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-31/raw/single_True_rag_True
Saved chunk 1 to /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation/2024-08-31/raw/single_True_rag_True/split_data/chunk_1.csv
Regenerating missing GPT-4 file for split data file: chunk_1.csv
Reading oneshot prompt from: /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt
Reading oneshot prompt done.
Building prompts for dataframe entries.
Calling GPT-4 API
剩余case 17 / 17
  0%|          | 0/17 [00:00<?, ?it/s]  6%|▌         | 1/17 [00:15<04:06, 15.40s/it] 24%|██▎       | 4/17 [00:17<00:46,  3.59s/it] 29%|██▉       | 5/17 [00:23<00:51,  4.28s/it] 35%|███▌      | 6/17 [00:31<00:57,  5.22s/it] 59%|█████▉    | 10/17 [00:45<00:29,  4.19s/it] 82%|████████▏ | 14/17 [00:51<00:08,  2.93s/it] 88%|████████▊ | 15/17 [00:57<00:06,  3.37s/it]100%|██████████| 17/17 [01:02<00:00,  3.07s/it]100%|██████████| 17/17 [01:02<00:00,  3.68s/it]
Parsing GPT-4 response
All GPT-4 files are generated and valid. Total files: 1
[INFO] end_time: 2024-09-02 22:03:26
[INFO] duration: 3 min 
